server:
    port: 80
    tomcat:
        uri-encoding: UTF-8
    servlet:
        context-path: /kudo

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/kudo?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: MYSQL
        show-sql: true
        generate-ddl: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                ddl-auto: update
    # ¾²Ì¬×ÊÔ´Â·¾¶
    resources:
        static-locations: classpath:static/,file:static/
kudo:
    jwt:
        secret: kudo-auth-@Jwt!&Secret^#
        expiration: 300000
        ignore-url: .*swagger.*, .*api-docs, .*\.js, .*\.css, .*\.png, /file/upload, /img/*, /config, .*
